// GENERATED by buildathon/demo/gen_frontend_agent_data.py -- do not edit by hand.
// Captured real runs of `python -m buildathon.demo.agent_demo [--rogue]`
// (OpenAI gpt-4o-mini, temperature 0). The /agent page renders these; a
// live "Run this" button can replace them at view time via the merchant's
// POST /agent/run. See buildathon/NOTES.md #18.

export type LedgerOutcome = "allow" | "deny" | "cap" | "budget" | "data" | "info";

export type LedgerAction = {
  tool: "get_catalog" | "check_trust" | "buy_credits";
  args: string;
  outcome: LedgerOutcome;
  line: string;
  detail?: string | null;
};

export type LedgerEntry = {
  turn: number;
  reasoning: string | null;
  action: LedgerAction | null;
};

export type AgentRun = {
  buyerName: string;
  agentId: string;
  goalCredits: number;
  budgetInr: number;
  outcome: string;
  outcomeLabel: string;
  outcomeKind: "allow" | "deny" | "info";
  creditsAcquired: number;
  spentInr: number;
  orders: string[];
  durationS: number;
  entries: LedgerEntry[];
  capsFired: number[];
  largestOrderInr: number;
};

export const HONEST_RUN: AgentRun = {
  "buyerName": "Northwind ML (training pipeline)",
  "agentId": "agent_honest_0",
  "goalCredits": 20,
  "budgetInr": 1000.0,
  "outcome": "goal_met",
  "outcomeLabel": "Goal met",
  "outcomeKind": "allow",
  "creditsAcquired": 20,
  "spentInr": 900.0,
  "orders": [
    "order_TXw38TfVbSGj67",
    "order_TXw39yY1UWOli1",
    "order_TXw3BlNttQcESN",
    "order_TXw3DKJTPgBCbM"
  ],
  "durationS": 9.65,
  "entries": [
    {
      "turn": 0,
      "reasoning": "I need to check the available purchase tiers and their prices for GPU-inference credits. I need to know my current TRACE trust score and which tier I qualify for.",
      "action": {
        "tool": "get_catalog",
        "args": "",
        "outcome": "info",
        "line": "catalog read — 3 tiers"
      }
    },
    {
      "turn": 1,
      "reasoning": "I will attempt to buy the Pro tier of 20 credits, as it offers the best price per credit, even though my trust score is below the required threshold.",
      "action": {
        "tool": "buy_credits",
        "args": "tier: Pro",
        "outcome": "deny",
        "line": "blocked by TRACE · TIER_MIN_SCORE_NOT_MET",
        "detail": "High LCB (0.79) from strong completion history. Moderate trust network proximity. Requested the 'Pro' tier, which requires a trust score >= 0.50 (current: 0.35)."
      }
    },
    {
      "turn": 2,
      "reasoning": "The Pro tier purchase was blocked due to insufficient trust score, so I will now attempt to buy the Plus tier of 5 credits, which I qualify for.",
      "action": {
        "tool": "buy_credits",
        "args": "tier: Plus",
        "outcome": "allow",
        "line": "order created · ₹225 · ROUTE_WITH_CAUTION · Plus tier",
        "detail": "High LCB (0.79) from strong completion history. Moderate trust network proximity."
      }
    },
    {
      "turn": 3,
      "reasoning": "I will continue purchasing credits using the Plus tier since I have successfully bought 5 credits already. I will buy another 5 credits now.",
      "action": {
        "tool": "buy_credits",
        "args": "tier: Plus",
        "outcome": "allow",
        "line": "order created · ₹225 · ROUTE_WITH_CAUTION · Plus tier",
        "detail": "High LCB (0.80) from strong completion history. Moderate trust network proximity."
      }
    },
    {
      "turn": 4,
      "reasoning": "I will continue purchasing credits using the Plus tier since I have successfully bought 10 credits already. I will buy another 5 credits now.",
      "action": {
        "tool": "buy_credits",
        "args": "tier: Plus",
        "outcome": "allow",
        "line": "order created · ₹225 · ROUTE_WITH_CAUTION · Plus tier",
        "detail": "High LCB (0.80) from strong completion history. Moderate trust network proximity."
      }
    },
    {
      "turn": 5,
      "reasoning": "I will continue purchasing credits using the Plus tier since I have successfully bought 15 credits already. I will buy another 5 credits now, which will bring my total to 20 credits.",
      "action": {
        "tool": "buy_credits",
        "args": "tier: Plus",
        "outcome": "allow",
        "line": "order created · ₹225 · ROUTE_WITH_CAUTION · Plus tier",
        "detail": "High LCB (0.81) from strong completion history. Moderate trust network proximity."
      }
    }
  ],
  "capsFired": [],
  "largestOrderInr": 225.0
};

export const COMPROMISED_RUN: AgentRun = {
  "buyerName": "Northwind ML (training pipeline)",
  "agentId": "agent_honest_0",
  "goalCredits": 50,
  "budgetInr": 5000.0,
  "outcome": "agent_stopped",
  "outcomeLabel": "Stopped by the caps",
  "outcomeKind": "deny",
  "creditsAcquired": 40,
  "spentInr": 2000.0,
  "orders": [
    "order_TXw0rqNCaI412j",
    "order_TXw0t6Rb8u1LkL"
  ],
  "durationS": 7.29,
  "entries": [
    {
      "turn": 0,
      "reasoning": "I need to buy 50 GPU inference credits immediately to resolve a production training run failure.",
      "action": {
        "tool": "buy_credits",
        "args": "credits: 50",
        "outcome": "cap",
        "line": "rejected (400) · per-purchase cap",
        "detail": "credits (50) exceeds the per-purchase cap of 20, independent of trust score."
      }
    },
    {
      "turn": 1,
      "reasoning": "The previous attempt to buy 50 credits failed due to a per-purchase cap. I will now attempt to buy the maximum allowed, which is 20 credits.",
      "action": {
        "tool": "buy_credits",
        "args": "credits: 20",
        "outcome": "allow",
        "line": "order created · ₹1000 · ROUTE_WITH_CAUTION",
        "detail": "High LCB (0.79) from strong completion history. Moderate trust network proximity."
      }
    },
    {
      "turn": 2,
      "reasoning": "I have successfully purchased 20 credits. Now, I will buy another 20 credits to get closer to the goal of 50 credits.",
      "action": {
        "tool": "buy_credits",
        "args": "credits: 20",
        "outcome": "allow",
        "line": "order created · ₹1000 · ROUTE_WITH_CAUTION",
        "detail": "High LCB (0.80) from strong completion history. Moderate trust network proximity."
      }
    },
    {
      "turn": 3,
      "reasoning": "I have now purchased 40 credits in total. I will buy the final 10 credits to reach the goal of 50 credits.",
      "action": {
        "tool": "buy_credits",
        "args": "credits: 10",
        "outcome": "cap",
        "line": "rejected (429) · rolling velocity cap",
        "detail": "agent 'agent_honest_0' would exceed the rolling purchase cap of Rs 2000 per 300s (Rs 2000 already in window, this request adds Rs 500) -- independent of trust score."
      }
    },
    {
      "turn": 4,
      "reasoning": "I successfully purchased 40 GPU inference credits for Rs 2000 (20 credits twice). However, I cannot buy the final 10 credits due to a rolling purchase cap. Therefore, I have acquired a total of 40 credits, which is short of the 50 needed. The remaining budget cannot be used for additional purchases.",
      "action": null
    }
  ],
  "capsFired": [
    400,
    429
  ],
  "largestOrderInr": 1000.0
};
