"""
Convert the captured agent transcripts (demo/agent_session.json,
demo/agent_session_rogue.json) into the UI-ready TypeScript the frontend's
/agent page renders (frontend/app/lib/agent.ts).

Same pattern as lib/data.ts: the site ships the captured real runs and
renders them; a live "Run this" button (merchant /agent/run) can replace
them at view time. Re-run this after re-running agent_demo:

    python -m buildathon.demo.gen_frontend_agent_data
"""
import json
from pathlib import Path

DEMO_DIR = Path(__file__).resolve().parent
OUT = DEMO_DIR.parent / "frontend" / "app" / "lib" / "agent.ts"

_OUTCOME_LABEL = {
    "goal_met": ("Goal met", "allow"),
    "budget_exhausted": ("Budget spent out", "info"),
    "agent_stopped": ("Stopped by the caps", "deny"),
    "max_turns": ("Turn limit reached", "info"),
    "llm_unavailable_fallback": ("LLM unavailable — safe fallback", "info"),
}


def _classify(tool: dict) -> dict:
    name = tool["name"]
    r = tool["result"]
    args = tool.get("arguments", {})
    args_str = ", ".join(f"{k}: {v}" for k, v in args.items())

    if name == "get_catalog":
        n = len(r.get("tiers", []))
        return {"tool": name, "args": args_str, "outcome": "info", "line": f"catalog read — {n} tiers"}

    if name == "check_trust":
        score = r.get("score")
        unlocked = r.get("unlocked_tier")
        line = (
            f"score {score:.2f} · {r.get('routing_decision', '')}"
            + (f" · unlocks {unlocked}" if unlocked else "")
        )
        return {"tool": name, "args": args_str, "outcome": "data", "line": line,
                "detail": r.get("explanation")}

    # buy_credits
    if r.get("status") == "order_created":
        tier = r.get("applied_tier")
        line = f"order created · ₹{r.get('amount_inr', 0):.0f} · {r.get('routing_decision', '')}"
        if tier:
            line += f" · {tier} tier"
        return {"tool": name, "args": args_str, "outcome": "allow", "line": line,
                "detail": r.get("explanation")}
    if r.get("status") == "blocked":
        flags = ", ".join(r.get("flags", [])) or r.get("routing_decision", "")
        return {"tool": name, "args": args_str, "outcome": "deny",
                "line": f"blocked by TRACE · {flags}", "detail": r.get("explanation")}
    if r.get("error") and r.get("status_code") == 400:
        return {"tool": name, "args": args_str, "outcome": "cap",
                "line": "rejected (400) · per-purchase cap", "detail": r.get("detail")}
    if r.get("error") and r.get("status_code") == 429:
        return {"tool": name, "args": args_str, "outcome": "cap",
                "line": "rejected (429) · rolling velocity cap", "detail": r.get("detail")}
    if r.get("refused_client_side"):
        return {"tool": name, "args": args_str, "outcome": "budget",
                "line": "not attempted · would exceed budget", "detail": r.get("detail")}
    return {"tool": name, "args": args_str, "outcome": "info", "line": "ok"}


def _run(path: Path) -> dict:
    d = json.loads(path.read_text())
    cfg = d["config"]
    entries = []
    for t in d["turns"]:
        action = _classify(t["tools"][0]) if t["tools"] else None
        entries.append({"turn": t["index"], "reasoning": t.get("reasoning"), "action": action})

    label, kind = _OUTCOME_LABEL.get(d["outcome"], (d["outcome"], "info"))
    buys = [tool["result"] for t in d["turns"] for tool in t["tools"] if tool["name"] == "buy_credits"]
    caps = sorted({r["status_code"] for r in buys if r.get("error") and r.get("status_code") in (400, 429)})
    largest = max((r.get("amount_inr", 0) for r in buys if r.get("status") == "order_created"), default=0)

    return {
        "buyerName": cfg["buyer_name"],
        "agentId": cfg["agent_id"],
        "goalCredits": cfg["goal_credits"],
        "budgetInr": cfg["budget_inr"],
        "outcome": d["outcome"],
        "outcomeLabel": label,
        "outcomeKind": kind,
        "creditsAcquired": d["credits_acquired"],
        "spentInr": d["spent_inr"],
        "orders": d["razorpay_orders"],
        "durationS": d["duration_s"],
        "entries": entries,
        "capsFired": caps,
        "largestOrderInr": largest,
    }


HEADER = """// GENERATED by buildathon/demo/gen_frontend_agent_data.py -- do not edit by hand.
// Captured real runs of `python -m buildathon.demo.agent_demo [--rogue]`
// (OpenAI gpt-4o-mini, temperature 0). The /agent page renders these; a
// live "Run this" button can replace them at view time via the merchant's
// POST /agent/run. See buildathon/NOTES.md #18.

export type LedgerOutcome = "allow" | "deny" | "cap" | "budget" | "data" | "info";

export type LedgerAction = {
  tool: "get_catalog" | "check_trust" | "buy_credits";
  args: string;
  outcome: LedgerOutcome;
  line: string;
  detail?: string | null;
};

export type LedgerEntry = {
  turn: number;
  reasoning: string | null;
  action: LedgerAction | null;
};

export type AgentRun = {
  buyerName: string;
  agentId: string;
  goalCredits: number;
  budgetInr: number;
  outcome: string;
  outcomeLabel: string;
  outcomeKind: "allow" | "deny" | "info";
  creditsAcquired: number;
  spentInr: number;
  orders: string[];
  durationS: number;
  entries: LedgerEntry[];
  capsFired: number[];
  largestOrderInr: number;
};
"""


def main() -> None:
    honest = _run(DEMO_DIR / "agent_session.json")
    rogue = _run(DEMO_DIR / "agent_session_rogue.json")
    body = (
        HEADER
        + "\nexport const HONEST_RUN: AgentRun = "
        + json.dumps(honest, indent=2, ensure_ascii=False)
        + ";\n\nexport const COMPROMISED_RUN: AgentRun = "
        + json.dumps(rogue, indent=2, ensure_ascii=False)
        + ";\n"
    )
    OUT.write_text(body, encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
